### ISSUE TITLE
Support run-perf for pull request each commit

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/test-infra#27]
When the `run-perf-master` label is added to the pull request, perf test should be run automatically for each commit of the pull request, instead of starting perf test with comment

**Comment by zhang2014** [comment]
CC: @ZhiHanZ

**Comment by sundy-li** [comment]
I suggest the perf tests default to run when all the other tests are passed. 

It measures whether the code changes introduced by a pull request influenced the performance, for which kinds of queries and by how much, and alerts the developer if there is a regression. 

https://clickhouse.tech/blog/en/2021/performance-test-1/

**Comment by BohuTANG** [comment]
The problem is that the perf test takes too long, most PRs not need(It's easy to check the PR diffs affect the performance or not).
The labe

> I suggest the perf tests default to run when all the other tests are passed.

The problem is that the perf test takes too long to run, most PRs may be not need(It's easy to check the PR diffs affect the performance or not for the review).
The labe

> It measures whether the code changes introduced by a pull request influenced the performance, for which kinds of queries and by how much, and alerts the developer if there is a regression.
> 
> https://clickhouse.tech/blog/en/2021/performance-test-1/

Personally, the `label` is good idea for now, and consider to run it for every PR later, such as our Alaph version released.

**Comment by BohuTANG** [comment]
Hi @ZhiHanZ 

Sundy and Winter ran into some issues where they found performance degradation with group by at some commits, but didn't know what was causing it, so it's make sense what Sundy said:
I suggest the perf tests default to run when all the other tests are passed.
